# Generated by Django 2.1.2 on 2018-12-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181222_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-time_stamp',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='posted',
            new_name='time_stamp',
        ),
    ]
