# Generated by Django 2.1.2 on 2018-12-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181223_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
