# Generated by Django 2.1.2 on 2018-12-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181223_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Submit')], default=0, verbose_name='Status'),
        ),
    ]
