# Generated by Django 2.1.2 on 2018-12-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20181224_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-submited_at',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-submited_at',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='active',
            new_name='approve',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='time_stamp',
            new_name='submited_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='approve',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='submited_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Submit')], default=0, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='post',
            name='approved_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars/', verbose_name='profile picture'),
        ),
    ]
